/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.thordrugstore.farmacia.view;

import br.com.thordrugstore.farmacia.DAO.FornecedorDAO;
import br.com.thordrugstore.farmacia.controller.FornecedorController;
import br.com.thordrugstore.farmacia.model.Fornecedor;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JHK
 */
public class TelaFornecedor extends javax.swing.JFrame {

    Fornecedor fornecedor;

    public TelaFornecedor() {
        initComponents();
        setLocationRelativeTo(null);
        fornecedor = new Fornecedor();
        carregarTabela();
    }

    public void validaNumerico(String confirma) {
        try {
            if (!confirma.matches("[0-9]*")) {
                JOptionPane.showMessageDialog(null, "Preencha o campo com valor numérico", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void validaString(String confirma) {
        try {
            if (confirma != null) {
                if (!confirma.matches("[A-z]*")) {
                    JOptionPane.showMessageDialog(null, "Este campo não pode ser preenchido com números");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void carregarTabela() {
        ArrayList<Fornecedor> listaFornecedores = FornecedorDAO.pesquisar();

        DefaultTableModel tabela = new DefaultTableModel();
        tabela.addColumn("ID");
        tabela.addColumn("razao_social");
        tabela.addColumn("cnpj");
        tabela.addColumn("telefone1");
        tabela.addColumn("telefone2");
        tabela.addColumn("celular");
        tabela.addColumn("endereco");
        tabela.addColumn("complemento");
        tabela.addColumn("cidade");
        tabela.addColumn("uf");

        tblFornecedores.setModel(tabela);

        tabela.setRowCount(0);

        for (Fornecedor f : listaFornecedores) {
            tabela.addRow(new Object[]{f.getFonecedorcod(), f.getRazaoSocial(), f.getCnpj(), f.getTelComercial1(), f.getTelComercial2(), f.getCelular(), f.getEndereco(), f.getComplemento(), f.getCidade(), f.getUf()});
        }
        tblFornecedores.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblFornecedores.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblFornecedores.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblFornecedores.getColumnModel().getColumn(3).setPreferredWidth(50);
        tblFornecedores.getColumnModel().getColumn(4).setPreferredWidth(50);
        tblFornecedores.getColumnModel().getColumn(5).setPreferredWidth(50);
        tblFornecedores.getColumnModel().getColumn(6).setPreferredWidth(50);
        tblFornecedores.getColumnModel().getColumn(7).setPreferredWidth(50);
        tblFornecedores.getColumnModel().getColumn(8).setPreferredWidth(50);
        tblFornecedores.getColumnModel().getColumn(9).setPreferredWidth(50);
    }

    public void setarCampos() {
        int setar = tblFornecedores.getSelectedRow();
        txtCodFornecedor.setText(tblFornecedores.getModel().getValueAt(setar, 0).toString());
        txtRazaoSocial.setText(tblFornecedores.getModel().getValueAt(setar, 1).toString());
        txtCnpj.setText(tblFornecedores.getModel().getValueAt(setar, 2).toString());
        txtTelComercial1.setText(tblFornecedores.getModel().getValueAt(setar, 3).toString());
        txtTelComercial2.setText(tblFornecedores.getModel().getValueAt(setar, 4).toString());
        txtCelular.setText(tblFornecedores.getModel().getValueAt(setar, 5).toString());
        txtEndereco.setText(tblFornecedores.getModel().getValueAt(setar, 6).toString());
        txtComplemento.setText(tblFornecedores.getModel().getValueAt(setar, 7).toString());
        txtCidade.setText(tblFornecedores.getModel().getValueAt(setar, 8).toString());
        txtUf.setText(tblFornecedores.getModel().getValueAt(setar, 9).toString());

        jButton3.setEnabled(false);
    }

    public void limparCampos() {
        txtCodFornecedor.setText(null);
        txtRazaoSocial.setText(null);
        txtCnpj.setText(null);
        txtTelComercial1.setText(null);
        txtTelComercial2.setText(null);
        txtCelular.setText(null);
        txtEndereco.setText(null);
        txtComplemento.setText(null);
        txtCidade.setText(null);
        txtUf.setText(null);

        jButton3.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUf = new javax.swing.JTextField();
        txtTelComercial1 = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtRazaoSocial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTelComercial2 = new javax.swing.JTextField();
        txtCodFornecedor = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPesquisarRazaoSocial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(37, 116, 169));

        txtUf.setBackground(new java.awt.Color(240, 240, 240));
        txtUf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUfMouseExited(evt);
            }
        });
        txtUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUfActionPerformed(evt);
            }
        });

        txtTelComercial1.setBackground(new java.awt.Color(240, 240, 240));
        txtTelComercial1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelComercial1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTelComercial1MouseExited(evt);
            }
        });

        txtEndereco.setBackground(new java.awt.Color(240, 240, 240));
        txtEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("UF:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("*Razão Social:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tel-Comercial 2:");

        txtCelular.setBackground(new java.awt.Color(240, 240, 240));
        txtCelular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCelularMouseExited(evt);
            }
        });

        txtRazaoSocial.setBackground(new java.awt.Color(240, 240, 240));
        txtRazaoSocial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRazaoSocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtRazaoSocialMouseExited(evt);
            }
        });
        txtRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaoSocialActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Endereço:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cidade:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cod_Fornecedor:");

        txtTelComercial2.setBackground(new java.awt.Color(240, 240, 240));
        txtTelComercial2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelComercial2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTelComercial2MouseExited(evt);
            }
        });

        txtCodFornecedor.setBackground(new java.awt.Color(240, 240, 240));
        txtCodFornecedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCodFornecedorMouseExited(evt);
            }
        });
        txtCodFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodFornecedorActionPerformed(evt);
            }
        });

        txtCidade.setBackground(new java.awt.Color(240, 240, 240));
        txtCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCidadeMouseExited(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("*CNPJ:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("*Tel-Comercial 1:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Celular:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Complemento:");

        txtComplemento.setBackground(new java.awt.Color(240, 240, 240));
        txtComplemento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });

        txtCnpj.setBackground(new java.awt.Color(240, 240, 240));
        txtCnpj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCnpj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCnpjMouseExited(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 177, 106));
        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(217, 30, 24));
        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fornecedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(txtCodFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelComercial1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelComercial2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(6, 6, 6)
                        .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2))
                    .addComponent(txtCodFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTelComercial1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtTelComercial2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8))
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtPesquisarRazaoSocial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPesquisarRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarRazaoSocialActionPerformed(evt);
            }
        });

        tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFornecedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPesquisarRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodFornecedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodFornecedorMouseExited
        validaNumerico(txtCodFornecedor.getText());
    }//GEN-LAST:event_txtCodFornecedorMouseExited

    private void txtTelComercial1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelComercial1MouseExited
        validaNumerico(txtTelComercial1.getText());
    }//GEN-LAST:event_txtTelComercial1MouseExited

    private void txtTelComercial2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelComercial2MouseExited
        validaNumerico(txtTelComercial2.getText());
    }//GEN-LAST:event_txtTelComercial2MouseExited

    private void txtCelularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCelularMouseExited
        validaNumerico(txtCelular.getText());
    }//GEN-LAST:event_txtCelularMouseExited

    private void txtCidadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCidadeMouseExited
        validaString(txtCidade.getText());
    }//GEN-LAST:event_txtCidadeMouseExited

    private void txtUfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUfMouseExited
        validaString(txtUf.getText());
    }//GEN-LAST:event_txtUfMouseExited

    private void txtUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUfActionPerformed

    private void txtRazaoSocialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRazaoSocialMouseExited
        validaString(txtRazaoSocial.getText());
    }//GEN-LAST:event_txtRazaoSocialMouseExited

    private void txtCnpjMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCnpjMouseExited
        validaNumerico(txtCnpj.getText());
    }//GEN-LAST:event_txtCnpjMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (txtRazaoSocial.getText().isEmpty() || txtCnpj.getText().isEmpty() || txtTelComercial1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios", "Atenção", JOptionPane.WARNING_MESSAGE);

            } else {
                int fornecedorcod = Integer.parseInt(txtCodFornecedor.getText());
                String razaoSocial = txtRazaoSocial.getText();
                String cnpj = txtCnpj.getText();
                String telComercial1 = txtTelComercial1.getText();
                String telComercial2 = txtTelComercial2.getText();
                String celular = txtCelular.getText();
                String endereco = txtEndereco.getText();
                String complemento = txtComplemento.getText();
                String cidade = txtCidade.getText();
                String uf = txtUf.getText();

                if (FornecedorController.salvar(fornecedorcod, razaoSocial, cnpj, telComercial1, telComercial2, celular, endereco, complemento, cidade, uf)) {
                    JOptionPane.showMessageDialog(this, "Fornecedor cadastrado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha no cadastro!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPesquisarRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarRazaoSocialActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (!txtCodFornecedor.getText().equals("")) {
            if (FornecedorController.excluir(Integer.valueOf(txtCodFornecedor.getText()))) {
                limparCampos();
            };
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if (txtRazaoSocial.getText().isEmpty() || txtCnpj.getText().isEmpty() || txtTelComercial1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha os campos obrigatorios");
            } else if (txtUf.getText().length() > 2) {
                JOptionPane.showMessageDialog(null, "O campo UF não pode conter mais que dois caracteres!", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {

                fornecedor.setFonecedorcod(Integer.parseInt(txtCodFornecedor.getText()));
                fornecedor.setRazaoSocial(txtRazaoSocial.getText());
                fornecedor.setCnpj(txtCnpj.getText());
                fornecedor.setTelComercial1(txtTelComercial1.getText());
                fornecedor.setTelComercial2(txtTelComercial2.getText());
                fornecedor.setCelular(txtCelular.getText());
                fornecedor.setEndereco(txtEndereco.getText());
                fornecedor.setComplemento(txtComplemento.getText());
                fornecedor.setCidade(txtCidade.getText());
                fornecedor.setUf(txtUf.getText());
                if (FornecedorController.atualizar(tblFornecedores, fornecedor)) {
                    JOptionPane.showMessageDialog(null, "Fornecedor cadastrado com sucesso!");
                    limparCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "Error dados não atualizados");
                }
            }
        } catch (NullPointerException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O campo salário não pode ser nulo, insira um valor maior ou igual a zero!", "Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Fornecedor> listaFornecedor;
        try {
            listaFornecedor = FornecedorDAO.pesquisar(txtPesquisarRazaoSocial.getText());

            DefaultTableModel tabela = new DefaultTableModel();
            tabela.addColumn("ID");
            tabela.addColumn("razao_social");
            tabela.addColumn("cnpj");
            tabela.addColumn("telefone1");
            tabela.addColumn("telefone2");
            tabela.addColumn("celular");
            tabela.addColumn("endereco");
            tabela.addColumn("complemento");
            tabela.addColumn("cidade");
            tabela.addColumn("uf");

            tblFornecedores.setModel(tabela);

            tabela.setRowCount(0);

            for (Fornecedor f : listaFornecedor) {
                tabela.addRow(new Object[]{f.getFonecedorcod(), f.getRazaoSocial(), f.getCnpj(), f.getTelComercial1(), f.getTelComercial2(), f.getCelular(), f.getEndereco(), f.getComplemento(), f.getCidade(), f.getUf()});
            }

            tblFornecedores.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(4).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(5).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(6).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(7).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(8).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(9).setPreferredWidth(50);

        } catch (ParseException ex) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedoresMouseClicked
        setarCampos();
    }//GEN-LAST:event_tblFornecedoresMouseClicked

    private void txtCodFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodFornecedorActionPerformed

    private void txtRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaoSocialActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFornecedores;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtCodFornecedor;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtPesquisarRazaoSocial;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtTelComercial1;
    private javax.swing.JTextField txtTelComercial2;
    private javax.swing.JTextField txtUf;
    // End of variables declaration//GEN-END:variables
}
